### ISSUE TITLE
只有model.py 

### ISSUE THREAD

**Issue by ahuczp** [gengyanlei/leilei#1]
怎么运行这个代码，训练集是什么，训练代码和inference.py,可以放出来吗？？

**Comment by gengyanlei** [comment]
@ahuczp 
您好，
首先声明一下，这不是本人的原创。但是，代码保证可以运行（已经运行过）
其次，每个人代码风格不同，很多人用argparse这个模块，我用过一次，感觉有点麻烦，因此按照我自己喜欢的方式来的。但是，和其他人对比，感觉有点low。所以没有放出来。
另外，给你发个链接，是bn注意事项。
http://www.cnblogs.com/hrlnw/p/7227447.html（转载）
主函数训练：网上很多，异曲同工。
HED是做边界检测用的，但是也可以用到语义分割上，可以做建筑物检测等语义分割任务。
